# -*- coding: utf-8 -*-
"""jundiai_bloco_g_modelos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10BoRY0kw_NHioe7SfPALkWvYjoax96A1

# Análise de Ilha de Calor Urbana — Jundiaí/SP
## Bloco G: Modelos de Machine Learning + Explicabilidade (SHAP)

Usa o DataFrame do Bloco F para treinar e comparar dois modelos não-lineares,
e interpreta as predições via SHAP values.

| Etapa | Descrição |
|-------|-----------|
| G1 | Carregamento e split estratificado por ano |
| G2 | Random Forest — treino, métricas, importância de features |
| G3 | XGBoost — treino e comparação |
| G4 | SHAP values — explicabilidade global e por classe |
| G5 | Mapa espacial de resíduos (onde o modelo erra?) |

---
## G1 — Setup e Carregamento
"""

# !pip install -q shap xgboost pyarrow contextily

import numpy as np, pandas as pd, matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from matplotlib.patches import Patch
import shap, os, warnings
warnings.filterwarnings('ignore')
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.inspection import permutation_importance
import xgboost as xgb
import rasterio
# from google.colab import drive
# drive.mount('/content/drive')

PASTA = '.'   # pasta local — figuras e rasters ficam no diretório do script
ANOS  = [2017, 2019, 2021, 2023, 2025]
np.random.seed(42)

df = pd.read_parquet('features_master.parquet')
print(f'✅ DataFrame carregado: {df.shape}')
print(f'   Anos: {sorted(df["ano"].unique())}')
print(f'   Classes: {sorted(df["mb_classe"].unique())}')

"""---
## G2 — Preparação das Features e Split

**Split estratificado por ano:** treino nos anos 2017, 2019, 2021, 2023 e
teste em 2025. Isso simula uma predição genuinamente temporal — o modelo
nunca viu dados de 2025 durante o treino. É mais rigoroso do que um split
aleatório, que vazaria informação temporal.
"""

FEATURES = ['NDVI','NDBI','MNDWI','NDVI2','NDBI_NDVI',
            'mb_urbanizado','mb_mosaico','mb_floresta','mb_pastagem',
            'mb_lavoura','mb_agua','mb_nao_vegetado','mb_outros']
TARGET   = 'LST_anomalia'

# Split temporal: treino = 2017-2023, teste = 2025
df_treino = df[df['ano'] < 2025].copy()
df_teste  = df[df['ano'] == 2025].copy()

X_train = df_treino[FEATURES].values
y_train = df_treino[TARGET].values
X_test  = df_teste[FEATURES].values
y_test  = df_teste[TARGET].values

print(f'Treino: {len(X_train):,} pixels (2017–2023)')
print(f'Teste:  {len(X_test):,}  pixels (2025)')
print(f'Features: {FEATURES}')

"""---
## G3 — Random Forest
"""

print('Treinando Random Forest...')
rf = RandomForestRegressor(
    n_estimators = 300,
    max_depth    = 15,
    min_samples_leaf = 50,   # evita overfitting por pixel
    n_jobs       = -1,
    random_state = 42
)
rf.fit(X_train, y_train)

y_pred_rf_train = rf.predict(X_train)
y_pred_rf_test  = rf.predict(X_test)

r2_train_rf  = r2_score(y_train, y_pred_rf_train)
r2_test_rf   = r2_score(y_test,  y_pred_rf_test)
mae_test_rf  = mean_absolute_error(y_test, y_pred_rf_test)

print(f'\n  Random Forest:')
print(f'  R² treino:  {r2_train_rf:.4f}')
print(f'  R² teste:   {r2_test_rf:.4f}   ← generalização temporal')
print(f'  MAE teste:  {mae_test_rf:.3f}°C')

# Importância de features (MDI — Mean Decrease Impurity)
importancias_rf = pd.Series(rf.feature_importances_, index=FEATURES)\
                    .sort_values(ascending=False)

fig, ax = plt.subplots(figsize=(10, 5))
cores_feat = ['#E74C3C' if 'mb_' not in f else '#3498DB' for f in importancias_rf.index]
importancias_rf.plot(kind='bar', ax=ax, color=cores_feat, edgecolor='white')
ax.set_title('Random Forest — Importância de Features (MDI)\n'
             'Vermelho = índice espectral  |  Azul = classe MapBiomas',
             fontweight='bold')
ax.set_ylabel('Importância relativa')
ax.set_xticklabels(importancias_rf.index, rotation=35, ha='right')
ax.grid(alpha=0.3, axis='y')
plt.tight_layout()
plt.savefig(f'{PASTA}/fig_G1_rf_importancia.png', dpi=150, bbox_inches='tight')
plt.show()
print('✅ fig_G1_rf_importancia.png salva')

"""---
## G4 — XGBoost
"""

print('Treinando XGBoost...')
xgb_model = xgb.XGBRegressor(
    n_estimators     = 400,
    max_depth        = 8,
    learning_rate    = 0.05,
    subsample        = 0.8,
    colsample_bytree = 0.8,
    min_child_weight = 50,
    tree_method      = 'hist',
    random_state     = 42,
    n_jobs           = -1
)
xgb_model.fit(X_train, y_train,
              eval_set=[(X_test, y_test)],
              verbose=False)

y_pred_xgb_test  = xgb_model.predict(X_test)
y_pred_xgb_train = xgb_model.predict(X_train)

r2_train_xgb = r2_score(y_train, y_pred_xgb_train)
r2_test_xgb  = r2_score(y_test,  y_pred_xgb_test)
mae_test_xgb = mean_absolute_error(y_test, y_pred_xgb_test)

print(f'\n  XGBoost:')
print(f'  R² treino:  {r2_train_xgb:.4f}')
print(f'  R² teste:   {r2_test_xgb:.4f}')
print(f'  MAE teste:  {mae_test_xgb:.3f}°C')

# Tabela comparativa
print('\n' + '='*50)
print('  COMPARAÇÃO RF vs XGBoost (teste = 2025)')
print('='*50)
print(f'  {"Modelo":<15} {"R² treino":>10} {"R² teste":>10} {"MAE (°C)":>10}')
print('-'*50)
print(f'  {"Random Forest":<15} {r2_train_rf:>10.4f} {r2_test_rf:>10.4f} {mae_test_rf:>10.3f}')
print(f'  {"XGBoost":<15} {r2_train_xgb:>10.4f} {r2_test_xgb:>10.4f} {mae_test_xgb:>10.3f}')
print('='*50)

"""---
## G5 — SHAP Values: Explicabilidade Global

SHAP (SHapley Additive exPlanations) decompõe cada predição na
contribuição individual de cada feature, **para cada pixel**.
É muito mais rico do que um coeficiente global — mostra como o efeito
de uma feature varia dependendo do seu valor e do contexto.

> ⏱️ O cálculo de SHAP para RF pode demorar 2–5 min.
"""

print('Calculando SHAP values (Random Forest)...')

# Amostra para SHAP — 10k pixels suficientes para o gráfico global
idx_shap = np.random.choice(len(X_test), min(10_000, len(X_test)), replace=False)
X_shap   = X_test[idx_shap]

explainer    = shap.TreeExplainer(rf)
shap_values  = explainer.shap_values(X_shap)

print(f'SHAP calculado para {len(X_shap):,} pixels.\n')

# ── Beeswarm (summary plot) ──────────────────────────────────────────────
plt.figure(figsize=(10, 7))
shap.summary_plot(shap_values, X_shap, feature_names=FEATURES,
                  show=False, plot_size=None)
plt.title('SHAP Values — Random Forest\nContribuição de cada feature na LST_anomalia',
          fontsize=13, fontweight='bold', pad=12)
plt.tight_layout()
plt.savefig(f'{PASTA}/fig_G2_shap_beeswarm.png', dpi=150, bbox_inches='tight')
plt.show()
print('✅ fig_G2_shap_beeswarm.png salva')

# ── Bar plot: importância SHAP média ─────────────────────────────────────
shap_mean = np.abs(shap_values).mean(axis=0)
shap_series = pd.Series(shap_mean, index=FEATURES).sort_values(ascending=True)

fig, ax = plt.subplots(figsize=(8, 6))
cores = ['#3498DB' if 'mb_' in f else '#E74C3C' for f in shap_series.index]
shap_series.plot(kind='barh', ax=ax, color=cores, edgecolor='white')
ax.set_xlabel('|SHAP| médio (°C)', fontsize=11)
ax.set_title('Importância Global via SHAP\nVermelho = espectral  |  Azul = MapBiomas',
             fontweight='bold')
ax.grid(alpha=0.3, axis='x')
plt.tight_layout()
plt.savefig(f'{PASTA}/fig_G3_shap_bar.png', dpi=150, bbox_inches='tight')
plt.show()
print('✅ fig_G3_shap_bar.png salva')

"""---
## G6 — SHAP por Classe MapBiomas

Mostra como o efeito de NDVI e NDBI na LST_anomalia **varia entre
classes de cobertura** — a não-linearidade que motivou o uso de RF.
"""

classes_plot = ['urbanizado','floresta','pastagem','agua']
features_foco = ['NDVI','NDBI','MNDWI','NDVI2','NDBI_NDVI']
idx_feat = [FEATURES.index(f) for f in features_foco]

fig, axes = plt.subplots(1, len(classes_plot), figsize=(16, 5), sharey=True)
fig.suptitle('SHAP Values por Classe MapBiomas — Features Espectrais\n'
             'Cada ponto = 1 pixel  |  cor = valor da feature',
             fontsize=13, fontweight='bold')

mb_classe_shap = df_teste['mb_classe'].values[idx_shap]

for ax, cls in zip(axes, classes_plot):
    mask = mb_classe_shap == cls
    if mask.sum() < 10:
        ax.set_title(f'{cls}\n(n={mask.sum()})')
        ax.axis('off'); continue

    sv_cls = shap_values[mask][:, idx_feat]
    bp = ax.boxplot([sv_cls[:, i] for i in range(len(features_foco))],
                   labels=features_foco, patch_artist=True,
                   medianprops=dict(color='black', lw=2))
    for patch in bp['boxes']: patch.set_alpha(0.7)
    ax.axhline(0, color='gray', lw=1, ls='--')
    ax.set_title(f'{cls}\n(n={mask.sum():,})', fontweight='bold')
    ax.set_xticklabels(features_foco, rotation=35, ha='right', fontsize=8)
    if ax == axes[0]: ax.set_ylabel('SHAP value (°C)')
    ax.grid(alpha=0.3, axis='y')

plt.tight_layout()
plt.savefig(f'{PASTA}/fig_G4_shap_por_classe.png', dpi=150, bbox_inches='tight')
plt.show()
print('✅ fig_G4_shap_por_classe.png salva')

"""---
## G7 — Mapa de Resíduos (2025)

Resíduo = LST_anomalia observada − LST_anomalia predita pelo RF.  
**Resíduo positivo** (vermelho) = o modelo subestimou — existe um fator
de aquecimento não capturado pelas features.  
**Resíduo negativo** (azul) = o modelo superestimou — área mais fria
do que as features sugerem.
"""

import contextily as ctx
import rasterio
# PASTA já definido no G1 (pasta local)

# Reconstrói o mapa de resíduos na grade de 2025
# (requer Jundiai_SUHI_2025.tif na pasta local)
with rasterio.open(f'{PASTA}/Jundiai_SUHI_2025.tif') as src:
    lst_2025 = src.read(1).astype(np.float32)
    bounds   = src.bounds
    src_meta = src.meta.copy()
EXT = [bounds.left, bounds.right, bounds.bottom, bounds.top]

# Máscara de pixels válidos de 2025 no df
df_2025  = df[df['ano'] == 2025].copy()
df_2025['residuo'] = y_test - y_pred_rf_test

# Reconstrói o raster de resíduos na grade do LST 2025.
# O Bloco F aplicou uma máscara mais estrita que a regra simples de nodata do
# LST (exige também índices espectrais/MapBiomas válidos): aqui há 325.507
# pixels "válidos", mas o parquet tem só 325.428 linhas para 2025. Para colocar
# cada resíduo no pixel certo, recupera-se a posição casando a coluna LST do
# parquet com o raster LST (mesma ordem row-major) — alinhamento por subsequência.
h, w       = lst_2025.shape
nodata     = (np.isnan(lst_2025)) | (lst_2025 <= 0) | (lst_2025 > 65)
valid_flat = np.flatnonzero(~nodata)              # índices row-major dos pixels válidos
lst_valid  = lst_2025.ravel()[valid_flat]
lst_parq   = df_2025['LST'].to_numpy(np.float32)

i = j = 0
flat_idx = np.empty(len(lst_parq), dtype=np.int64)
while j < len(lst_parq) and i < len(lst_valid):
    if lst_valid[i] == lst_parq[j]:
        flat_idx[j] = valid_flat[i]
        i += 1; j += 1
    else:
        i += 1                                    # pixel descartado pelo Bloco F
assert j == len(lst_parq), f'alinhamento LST incompleto ({j}/{len(lst_parq)})'
assert (lst_2025.ravel()[flat_idx] == lst_parq).all(), 'alinhamento LST inconsistente'

res_map = np.full(h * w, np.nan, dtype=np.float32)
res_map[flat_idx] = df_2025['residuo'].values
res_map = res_map.reshape(h, w)

lim = np.nanpercentile(np.abs(res_map), 98)

fig, ax = plt.subplots(figsize=(11, 9))
ax.set_xlim(EXT[0], EXT[1]); ax.set_ylim(EXT[2], EXT[3])
try:
    ctx.add_basemap(ax, crs='EPSG:4326',
                    source=ctx.providers.OpenStreetMap.Mapnik,
                    alpha=0.35, zorder=0)
except: pass
im = ax.imshow(res_map, extent=EXT, cmap='RdBu_r', vmin=-lim, vmax=lim,
               alpha=0.82, zorder=1, origin='upper')
plt.colorbar(im, ax=ax, label='Resíduo (°C)', fraction=0.046, pad=0.04)
ax.set_title(f'Mapa de Resíduos — Random Forest (2025)\n'
             f'Vermelho = subestimado  |  Azul = superestimado\n'
             f'MAE: {mae_test_rf:.3f}°C  |  R²: {r2_test_rf:.4f}',
             fontsize=12, fontweight='bold')
ax.set_xlabel('Longitude'); ax.set_ylabel('Latitude')
plt.tight_layout()
plt.savefig(f'{PASTA}/fig_G5_mapa_residuos.png', dpi=150, bbox_inches='tight')
plt.show()
print('✅ fig_G5_mapa_residuos.png salva')

# Exportar matriz de resíduos para o Streamlit
out_meta = src_meta.copy()
out_meta.update({
    "dtype": "float32",
    "count": 1,
    "nodata": np.nan
})

caminho_tif_residuos = f'{PASTA}/Jundiai_Residuos_2025.tif'
with rasterio.open(caminho_tif_residuos, 'w', **out_meta) as dest:
    dest.write(res_map, 1)

print(f'✅ Arquivo {caminho_tif_residuos} salvo para o dashboard.')

"""---
## Figuras Geradas

| Arquivo | Conteúdo |
|---------|----------|
| `fig_F1_boxplot_classes.png` | LST_anomalia por classe MapBiomas |
| `fig_G1_rf_importancia.png`  | Importância MDI — Random Forest |
| `fig_G2_shap_beeswarm.png`   | SHAP beeswarm — todas as features |
| `fig_G3_shap_bar.png`        | SHAP médio por feature |
| `fig_G4_shap_por_classe.png` | SHAP por classe MapBiomas |
| `fig_G5_mapa_residuos.png`   | Mapa espacial de resíduos (2025) |

---
**Próximo passo:** Bloco D — Mapa de Persistência com basemap corrigido.
"""

